[package]
name = "rust_tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ndarray = "0.15.4"
tui = "0.18"
crossterm = "0.23"
unicode-width = "0.1.5"